# FlewOS & FlewUI version
PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0

FLEWUI_VERSION = $(LINEAGE_VERSION)

# Internal version
LINEAGE_VERSION := FlewOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%d%m%Y)-$(LINEAGE_BUILD)-$(PLATFORM_VERSION)-ALPHA

# Display version
LINEAGE_DISPLAY_VERSION := FlewOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-$(PLATFORM_VERSION)-ALPHA
